###

GET http://localhost:3200/todos HTTP/1.1

###

POST http://localhost:3200/todos HTTP/1.1
content-type: application/json

{
    "description": "Learn mongoDB",
    "done": false,
    "targetDate": "2024-01-04"
}

###

POST http://localhost:3200/todos HTTP/1.1
content-type: application/json

{
    "description": "Learn nestJS",
    "done": false,
    "targetDate": "2024-02-01"
}

###

POST http://localhost:3200/todos HTTP/1.1
content-type: application/json

{
    "description": "Learn nextJS",
    "done": false,
    "targetDate": "2024-03-01"
}

###

GET http://localhost:3200/todos/658f09c1a4bb4fb4fd981870 HTTP/1.1

###