GET http://localhost:3200/todos HTTP/1.1

###

POST http://localhost:3200/todos HTTP/1.1
content-type: application/json

{
    "description": "Learn mongoDB",
    "done": false,
    "targetDate": "2024-01-04"
}

###

POST http://localhost:3200/todos HTTP/1.1
content-type: application/json

{
    "description": "Learn nestJS",
    "done": false,
    "targetDate": "2024-02-01"
}

###

GET http://localhost:3200/todos/1234 HTTP/1.1

###